options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build the container image with build args
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--platform=linux/amd64',
      '-t', 'gcr.io/$PROJECT_ID/fait-coop-sveltekit:$COMMIT_SHA',
      '-f', 'Dockerfile.sveltekit',
      '--build-arg', 'VITE_SUPABASE_URL=${_VITE_SUPABASE_URL}',
      '--build-arg', 'VITE_SUPABASE_ANON_KEY=${_VITE_SUPABASE_ANON_KEY}',
      '--build-arg', 'VITE_GOOGLE_CLIENT_ID=${_VITE_GOOGLE_CLIENT_ID}',
      '--build-arg', 'VITE_GOOGLE_MAPS_API_KEY=${_VITE_GOOGLE_MAPS_API_KEY}',
      '--build-arg', 'VITE_STRIPE_PUBLIC_KEY=${_VITE_STRIPE_PUBLIC_KEY}',
      '--build-arg', 'STRIPE_SECRET_KEY=${_STRIPE_SECRET_KEY}',
      '--build-arg', 'SUPABASE_SERVICE_KEY=${_SUPABASE_SERVICE_KEY}',
      '--build-arg', 'SUPABASE_SERVICE_ROLE_KEY=${_SUPABASE_SERVICE_ROLE_KEY}',
      '--build-arg', 'JWT_SECRET=${_JWT_SECRET}',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fait-coop-sveltekit:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - fait-coop-sveltekit
      - --image=gcr.io/$PROJECT_ID/fait-coop-sveltekit:$COMMIT_SHA
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated

# Default values for substitution variables
substitutions:
  _VITE_SUPABASE_URL: ""
  _VITE_SUPABASE_ANON_KEY: ""
  _VITE_GOOGLE_CLIENT_ID: ""
  _VITE_GOOGLE_MAPS_API_KEY: ""
  _VITE_STRIPE_PUBLIC_KEY: ""
  _STRIPE_SECRET_KEY: ""
  _SUPABASE_SERVICE_KEY: ""
  _SUPABASE_SERVICE_ROLE_KEY: ""
  _JWT_SECRET: ""

images:
  - gcr.io/$PROJECT_ID/fait-coop-sveltekit:$COMMIT_SHA
