export const TRADE_OPTIONS = [
  "Demolition & Disposal",
  "Electrical",
  "Plumbing",
  "Carpentry / Framing",
  "Window Installation",
  "Flooring",
  "Insulation",
  "Tile",
  "Shower Glass Installation",
  "Drywall",
  "Painting",
  "Storage Solutions",
  "HVAC",
  "Roofing",
  "Siding",
  "Deck Building",
  "Cabinetry",
  "Countertop Installation",
  "Appliance Installation",
  "Lighting & Fixtures",
  "Door Installation",
  "Custom Closets & Shelving",
  "Smart Home Integration",
  "Permitting & Inspection Services",
  "Finish Carpentry",
  "Waterproofing",
  "Soundproofing",
  "Fireplace Installation",
  "Accessibility Modifications"
];
