runtime: python39
entrypoint: gunicorn -b :$PORT cloud_app:app

env_variables:
  BIGBOX_API_KEY: "52323740B6D14CBE81D81C81E0DD32E6"

# Automatic scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 2
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: automatic

# Use the F1 (free tier) instance class
instance_class: F1

# Handlers for static files (if needed)
handlers:
- url: /.*
  script: auto
